# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_ml <- function(x) {
    .Call(`_GraphSPME_cov_ml`, x)
}

.cov_shrink_spd <- function(x) {
    .Call(`_GraphSPME_cov_shrink_spd`, x)
}

.prec_sparse <- function(x, Z, cov_shrinkage = TRUE) {
    .Call(`_GraphSPME_prec_sparse`, x, Z, cov_shrinkage)
}

