# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cov_shrink_spd <- function(x) {
    .Call(`_GraphSPME__cov_shrink_spd`, x)
}

.sparse_matrix_inverse <- function(A) {
    .Call(`_GraphSPME__sparse_matrix_inverse`, A)
}

.prec_sparse <- function(x, Neighbours, markov_order = 1L, cov_shrinkage = TRUE) {
    .Call(`_GraphSPME__prec_sparse`, x, Neighbours, markov_order, cov_shrinkage)
}

.cov_ml <- function(x) {
    .Call(`_GraphSPME__cov_ml`, x)
}

.create_bi <- function(Z, j) {
    .Call(`_GraphSPME__create_bi`, Z, j)
}

.get_precision_nonzero <- function(Graph, markov_order) {
    .Call(`_GraphSPME__get_precision_nonzero`, Graph, markov_order)
}

.prec_nll <- function(X, Prec) {
    .Call(`_GraphSPME__prec_nll`, X, Prec)
}

.prec_aic <- function(X, Prec) {
    .Call(`_GraphSPME__prec_aic`, X, Prec)
}

